ultimoprogetto/Controllers/AgiungieModificaPizzaController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Web.UI.WebControls;
using ultimoprogetto.Models;

namespace ultimoprogetto.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AgiungieModificaPizzaController : Controller
    {
        // GET: AgiungieModificaPizza
        public ActionResult creapizza()
        {
            return View();
        }

        [HttpPost]
        public ActionResult creapizza(pizza p, HttpPostedFileBase img)
        {
            if (ModelState.IsValid)
            {
                if (p.img != null)
                {
                    string nomeFile = img.FileName;
                    string pathToSave = Path.Combine(Server.MapPath("~/Content/FileUpload"), nomeFile);
                    img.SaveAs(pathToSave);
                    p.img = nomeFile;
                    Model1 model = new Model1();
                    model.pizza.Add(p);
                    model.SaveChanges();
                }
                else { ViewBag.pizza = "si prega di inserire un immagine"; }
            }
            return View();
        }

        public ActionResult eliminapizzadaldatabase(string parameter)
        {
            int i = Convert.ToInt32(parameter);
            Model1 model = new Model1();
            pizza p = model.pizza.FirstOrDefault((e) => e.idpizza == i);
            model.pizza.Remove(p);
            model.SaveChanges();
            return RedirectToAction("menu", "MenuOrdinazioni");
        }

        [HttpGet]
        public ActionResult modificapizza(int id)
        {
            Model1 model = new Model1();
            pizza p = model.pizza.FirstOrDefault((e) => e.idpizza == id);
            Session["img"] = p.img;
            return View(p);
        }

        [HttpPost]
        public ActionResult modificapizza(pizza p, HttpPostedFileBase img)
        {
            if (ModelState.IsValid)
            {
                Model1 model = new Model1();
                if (p.img == null)
                {
                    p.img = Session["img"].ToString();
                }
                else
                {
                    string nomeFile = img.FileName;
                    string pathToSave = Path.Combine(Server.MapPath("~/Content/FileUpload"), nomeFile);
                    img.SaveAs(pathToSave);
                    p.img = nomeFile;
                    Session["img"] = p.img;
                }
                model.Entry(p).State = EntityState.Modified;
                model.SaveChanges();
            }
            return View(p);
        }

        public ActionResult evadi(string parameter)
        {
            int id = int.Parse(parameter);
            Model1 model = new Model1();
            ordini ordini = model.ordini.Find(id);
            ordini.evaso = true;
            model.Entry(ordini).State = EntityState.Modified;
            model.SaveChanges();
            return RedirectToAction("listaord", "MenuOrdinazioni");
        }
    }
}

ultimoprogetto/Views/AgiungieModificaPizza/creapizza.cshtml
@model ultimoprogetto.Models.pizza

@{
    ViewBag.Title = "creapizza";
}

<h2>creapizza</h2>

@using (Html.BeginForm("creapizza", "AgiungieModificaPizza", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>pizza</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.costo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.costo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.costo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.img, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.img, new { @class = "form-control", type = "file", @accept = "image/*" })
                @Html.ValidationMessageFor(model => model.img, "", new { @class = "text-danger" })
                <p class="text-danger"> @ViewBag.pizza </p>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ingredienti, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ingredienti, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ingredienti, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nome, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.tempoConsegnamin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tempoConsegnamin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tempoConsegnamin, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btnb mt-1" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ultimoprogetto/Views/AgiungieModificaPizza/modificapizza.cshtml
@model ultimoprogetto.Models.pizza

@{
    ViewBag.Title = "modificapizza";
}

<h2>modificapizza</h2>

@using (Html.BeginForm("modificapizza", "AgiungieModificaPizza", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>pizza</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idpizza)

        <div class="form-group">
            @Html.LabelFor(model => model.costo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.costo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.costo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.img, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.img, new { @class = "form-control", type = "file", @accept = "image/*" })
                @Html.ValidationMessageFor(model => model.img, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ingredienti, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ingredienti, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ingredienti, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nome, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.tempoConsegnamin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tempoConsegnamin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tempoConsegnamin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="modifica la pizza @Model.nome" class="btn btnb mt-1" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>